Bulk update settings
Stanford-Online/edx-platform pull request #895
Opened 2019-06-20 22:59 UTC by tanyaxp

This replaces 
https://github.com/tanyaxp/edx-platform/pull/1
#681

2019-06-24 19:07 UTC, tanyaxp commented
@stvstnfrd Please review my code. Thanks!

2019-06-25 15:55 UTC, stvstnfrd requested changes
Just a few minor things.
I didn't have a chance to run the tests locally, so please ask one of the other developers to try it out.

2019-06-25 15:55 UTC, stvstnfrd commented on cms/envs/devstack.py
> +FEATURES['ENABLE_SERVICE_STATUS'] = True
I think we can remove this?

What does it do?

2019-06-25 15:55 UTC, stvstnfrd commented on lms/envs/devstack.py
> +CELERY_ALWAYS_EAGER = False
This should presumably be switched back to `True`, right?

2019-06-25 15:55 UTC, stvstnfrd commented on lms/envs/devstack.py
> +FEATURES['ENABLE_SERVICE_STATUS'] = True
Like the CMS equivalent, I think we can remove this?

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/static/js/factories/bulkupdate.js
> +                data.maxAttempts = parseInt($maxAttempts.val(),10);
Style: space after the comma.

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/static/js/factories/bulkupdate.js
> +            if (showAnswer && SHOW_ANSWER_OPTIONS.indexOf(showAnswer) < 0) {
Can we drop the left-hand side here?
This one does seem redundant..

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/static/js/factories/bulkupdate.js
> +                errMsg = '';
Should we display the exception text as the error message?

It seems a little weird that our error-handling in our error-handling doesn't display an error :)

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/static/js/factories/bulkupdate.js
> +                    success: onSuccess,
Cool, this is looking good now.

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/tests/test_bulkupdate.py
> +        Operations is not supported (PUT, DELETE).
Nitpick: grammar?

`Operations is ...`

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/tests/test_bulkupdate.py
> +                "{}'s bulk update on {}".format(self.user.username, self.course.display_name),
I think this is still testing the old way we were sending emails?

2019-06-25 15:55 UTC, stvstnfrd commented on openedx/stanford/cms/djangoapps/contentstore/views/utilities/tasks.py
> +        detail_url = reverse('utility_bulksettings_handler',kwargs={'course_key_string': course.id,})
If we're going to use the `reverse_course_url` (or whatever) helper, we should use it everywhere.

2019-07-09 22:01 UTC, stvstnfrd requested changes
Just a few cleanup items

Remember to run quality checks for linting errors.

There also appears to be a bit of unused code following previous refactoring (unused imports, unused exception handling, etc.). I think I caught them all, but can you double-check?

2019-07-12 00:11 UTC, tanyaxp commented on openedx/stanford/cms/djangoapps/contentstore/tests/test_bulkupdate.py
> +from django.core import mail
Mail here is used to check if the test email has reached the outbox

2019-07-12 21:57 UTC, merged